ci_service: travis_ci
coverage_service: coveralls
xcodeproj: InterfaceUtilities-Swift.xcodeproj
scheme: InterfaceUtilities
source_directory: InterfaceUtilities
workspace: InterfaceUtilities-Swift.xcworkspace